USE [master]
GO

/****** Object:  Database [FITCARD]    Script Date: 20/10/2018 14:19:05 ******/
CREATE DATABASE [FITCARD]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'FITCARD', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\FITCARD.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'FITCARD_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\FITCARD_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [FITCARD] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [FITCARD].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [FITCARD] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [FITCARD] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [FITCARD] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [FITCARD] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [FITCARD] SET ARITHABORT OFF 
GO

ALTER DATABASE [FITCARD] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [FITCARD] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [FITCARD] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [FITCARD] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [FITCARD] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [FITCARD] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [FITCARD] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [FITCARD] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [FITCARD] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [FITCARD] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [FITCARD] SET  DISABLE_BROKER 
GO

ALTER DATABASE [FITCARD] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [FITCARD] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [FITCARD] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [FITCARD] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [FITCARD] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [FITCARD] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [FITCARD] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [FITCARD] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [FITCARD] SET  MULTI_USER 
GO

ALTER DATABASE [FITCARD] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [FITCARD] SET DB_CHAINING OFF 
GO

ALTER DATABASE [FITCARD] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [FITCARD] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [FITCARD] SET  READ_WRITE 
GO


