USE [FITCARD]
GO

/****** Object:  StoredProcedure [dbo].[READ_ESTAB]    Script Date: 20/10/2018 14:03:49 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[READ_ESTAB]
	@ID_ESTAB INT 
AS
BEGIN
		SELECT * FROM ESTABELECIMENTO NOLOCK WHERE IDESTABELECIMENTO = @ID_ESTAB
END
GO


