USE [FITCARD]
GO

/****** Object:  StoredProcedure [dbo].[UPDATE_ESTAB]    Script Date: 20/10/2018 14:04:09 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[UPDATE_ESTAB]
	@ID_ESTAB INT, 
	@CNPJ varchar(14),
	@RAZAO_SOCIAL VARCHAR(250),
	@NOME_FANTASIA VARCHAR(250) = NULL,
	@EMAIL VARCHAR(100) = NULL,
	@ENDERECO VARCHAR(MAX) = NULL,
	@CIDADE VARCHAR(150) = NULL,
	@ESTADO VARCHAR(2) = NULL,
	@TELEFONE VARCHAR(14) = NULL,
	@CATEGORIA VARCHAR(150) = NULL,
	@STATUS BIT = NULL,
	@AGENCIA VARCHAR(4) = NULL,
	@CONTA VARCHAR(6) = NULL
AS
BEGIN
	BEGIN TRY
		--INICIA A TRANSAÇÃO
		BEGIN TRANSACTION
		
		--ATUALIZA OS DADOS VINDO DA PROCEDURE
		UPDATE ESTABELECIMENTO SET
								 CNPJ			= @CNPJ, 
								 RAZAOSOCIAL	= @RAZAO_SOCIAL,
								 NOMEFANTASIA	= @NOME_FANTASIA,
								 EMAIL			= @EMAIL,
								 ENDERECO		= @ENDERECO,
								 CIDADE			= @CIDADE,
								 ESTADO			= @ESTADO,
								 TELEFONE		= @TELEFONE,
								 CATEGORIA		= @CATEGORIA,
								 STATUS			= @STATUS,
								 AGENCIA		= @AGENCIA,
								 CONTA			= @CONTA
		WHERE IDESTABELECIMENTO = @ID_ESTAB 

		--VERIFICA SE APRESENTOU ALGUM ERRO.
		IF @@ERROR = 0
		BEGIN
			COMMIT
			SELECT COD_ERRO = 0, RETORNO = 'Estabelecimento alterado com sucesso.' 
		END	
		ELSE
		BEGIN
			ROLLBACK
			SELECT COD_ERRO = 1, RETORNO = 'Erro ao alterar o estabelecimento.' 
		END
	END TRY 
	BEGIN CATCH
	  SELECT COD_ERRO = 1, RETORNO = ERROR_MESSAGE()
	END CATCH
END
GO


