USE [FITCARD]
GO

/****** Object:  StoredProcedure [dbo].[DELETE_ESTAB]    Script Date: 20/10/2018 14:02:49 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[DELETE_ESTAB]
	@ID_ESTAB INT
AS
BEGIN
	BEGIN TRY
		--INICIA A TRANSAÇÃO
		BEGIN TRANSACTION
		
		--DELETE O ESTABELECIMENTO
		DELETE FROM ESTABELECIMENTO
		WHERE IDESTABELECIMENTO = @ID_ESTAB 

		--VERIFICA SE APRESENTOU ALGUM ERRO.
		IF @@ERROR = 0
		BEGIN
			COMMIT
			SELECT COD_ERRO = 0, RETORNO = 'Estabelecimento excluído com sucesso.' 
		END	
		ELSE
		BEGIN
			ROLLBACK
			SELECT COD_ERRO = 1, RETORNO = 'Erro ao excluir estabelecimento.' 
		END
	END TRY 
	BEGIN CATCH
	  SELECT COD_ERRO = 1, RETORNO = ERROR_MESSAGE()
	END CATCH
END
GO


