USE [FITCARD]
GO

/****** Object:  StoredProcedure [dbo].[INSERT_ESTAB]    Script Date: 20/10/2018 14:03:06 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[INSERT_ESTAB]
	@CNPJ varchar(14),
	@RAZAO_SOCIAL VARCHAR(250),
	@NOME_FANTASIA VARCHAR(250) = NULL,
	@EMAIL VARCHAR(100) = NULL,
	@ENDERECO VARCHAR(MAX) = NULL,
	@CIDADE VARCHAR(150) = NULL,
	@ESTADO VARCHAR(2) = NULL,
	@TELEFONE VARCHAR(14) = NULL,
	@CATEGORIA VARCHAR(150) = NULL,
	@STATUS BIT = NULL,
	@AGENCIA VARCHAR(4) = NULL,
	@CONTA VARCHAR(6) = NULL,
	@DATACRIACAO DATETIME = NULL
AS
BEGIN
	BEGIN TRY
	  -- VERIFICA SE JÁ EXISTE O CNPJ CADASTRADO, SE EXISTIR RETORNA COM A MENSAGEM DE "CNPJ JÁ CADASTRADO NO SISTEMA"
	  IF EXISTS(SELECT CNPJ FROM ESTABELECIMENTO NOLOCK WHERE CNPJ = @CNPJ) 
	  BEGIN
		SELECT COD_ERRO = 1, RETORNO = 'CNPJ já cadastrado.' 
	  END
	  ELSE
	  BEGIN
		--INICIA A TRANSAÇÃO
		BEGIN TRANSACTION
		
		--INSERE OS DADOS VINDO DA PROCEDURE
		INSERT INTO ESTABELECIMENTO VALUES (@CNPJ, @RAZAO_SOCIAL, @NOME_FANTASIA, @EMAIL, @ENDERECO, @CIDADE, @ESTADO, @TELEFONE, @DATACRIACAO, @CATEGORIA, @STATUS, @AGENCIA, @CONTA)

		--VERIFICA SE APRESENTOU ALGUM ERRO.
		IF @@ERROR = 0
		BEGIN
			COMMIT
			SELECT COD_ERRO = 0, RETORNO = 'Estabelecimento cadastrado com sucesso.' 
		END	
		ELSE
		BEGIN
			ROLLBACK
			SELECT COD_ERRO = 1, RETORNO = 'Erro ao cadastrar estabelecimento.' 
		END
	  END
	END TRY 
	BEGIN CATCH
	  SELECT COD_ERRO = 1, RETORNO = ERROR_MESSAGE()
	END CATCH
END
GO


